name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'There has been no activity on this issue for over 60 days. If there is no further activity within 7 days from this message, it will be automatically closed.'
        stale-pr-message: 'There has been no activity on this pull request for over 60 days. If there is no further activity within 7 days from this message, it will be automatically rejected.'
        stale-issue-label: 'no-issue-activity'
        stale-pr-label: 'no-pr-activity'
        exempt-issue-labels: 'on-hold'
        exempt-pr-labels: 'on-hold'
        
